/**
 * Demo data seed — every firm, account and trade here is fictional.
 *
 *   npm run db:seed        (creates/replaces the demo user)
 *
 * Demo login: demo@proptrack.test / demo-password-123
 *
 * Trades are generated by a seeded PRNG so the dataset is identical on every run. Account
 * outcomes (passed, breached, funded with payouts, in progress) are produced by scenario
 * controllers; the stored statuses are then checked against what the rule engine computes.
 */
import "dotenv/config";
import { hashPassword } from "better-auth/crypto";
import type { AccountEventType, AccountStatus, AccountType, Direction, DrawdownType, TradeGrade } from "../src/generated/prisma/enums";
import { prisma } from "../src/server/db";
import { provisionNewUser } from "../src/server/services/provision";
import { rebuildAccount } from "../src/server/services/rebuild";
import { getAccountState } from "../src/server/queries/accounts";
import { tradeFingerprint } from "../src/lib/import/fingerprint";

const DEMO_EMAIL = "demo@proptrack.test";
const DEMO_PASSWORD = "demo-password-123";
const LAST_DAY = "2026-09-25";

// ─── Deterministic randomness ───────────────────────────────────────────────
let seed = 20260927;
function rand() {
  seed = (seed * 1664525 + 1013904223) % 4294967296;
  return seed / 4294967296;
}
const between = (a: number, b: number) => a + (b - a) * rand();
const int = (a: number, b: number) => Math.floor(between(a, b + 1));
const pick = <T,>(xs: readonly T[]) => xs[Math.floor(rand() * xs.length)];
const chance = (p: number) => rand() < p;

// ─── Market model ───────────────────────────────────────────────────────────
interface Inst {
  symbol: string;
  price: number;
  vol: number;
  stop: [number, number];
  pointValue: number;
  lotStep: number;
  tick: number;
  commissionPerLot: number;
}
const INSTRUMENTS: Record<string, Inst> = {
  EURUSD: { symbol: "EURUSD", price: 1.0950, vol: 0.004, stop: [0.0012, 0.003], pointValue: 100000, lotStep: 0.01, tick: 0.00001, commissionPerLot: 7 },
  GBPUSD: { symbol: "GBPUSD", price: 1.2750, vol: 0.005, stop: [0.0015, 0.0035], pointValue: 100000, lotStep: 0.01, tick: 0.00001, commissionPerLot: 7 },
  XAUUSD: { symbol: "XAUUSD", price: 2380, vol: 12, stop: [2.5, 6], pointValue: 100, lotStep: 0.01, tick: 0.01, commissionPerLot: 7 },
  NAS100: { symbol: "NAS100", price: 18800, vol: 120, stop: [20, 45], pointValue: 1, lotStep: 0.1, tick: 0.1, commissionPerLot: 0 },
  US30: { symbol: "US30", price: 39800, vol: 180, stop: [40, 90], pointValue: 1, lotStep: 0.1, tick: 1, commissionPerLot: 0 },
  BTCUSD: { symbol: "BTCUSD", price: 64000, vol: 900, stop: [300, 700], pointValue: 1, lotStep: 0.01, tick: 0.01, commissionPerLot: 0 },
};
const roundTo = (x: number, step: number) => Math.round(x / step) * step;
const fix = (x: number, step: number) => Number(roundTo(x, step).toFixed(Math.max(0, -Math.floor(Math.log10(step)))));

function nextPrice(inst: Inst) {
  inst.price = Math.max(inst.price * 0.5, inst.price + (rand() - 0.5) * inst.vol);
  return inst.price;
}

const STRATEGIES = ["Breakout", "Pullback", "Reversal", "Trend continuation", "Liquidity sweep", "Support/resistance"] as const;
// Strategy edges differ so strategy analytics have something real to show.
const STRATEGY_EDGE: Record<string, number> = { Breakout: 0.03, Pullback: 0.07, Reversal: -0.06, "Trend continuation": 0.05, "Liquidity sweep": 0.02, "Support/resistance": 0 };
const SETUPS = ["Break & retest", "Opening range breakout", "Double top/bottom", "Flag", "Range fade", "Stop hunt"];
const TIMEFRAMES = ["M5", "M15", "M15", "H1"];
const CONDITIONS = ["Trending", "Ranging", "Volatile", "Low volatility"];
const CONFLUENCES = ["HTF trend", "Key level", "Liquidity", "Fair value gap", "Volume", "Session open"];

const THESES: Record<string, string[]> = {
  Breakout: ["Range compression under resistance; expecting expansion on the session open.", "Clean break of the Asian high with volume."],
  Pullback: ["Pullback into prior breakout level within an HTF uptrend.", "Retest of the 20 EMA after impulsive move."],
  Reversal: ["Exhaustion wick at daily level; looking for mean reversion.", "Divergence at the high of day."],
  "Trend continuation": ["Higher lows holding; continuation after flag.", "Trend day structure, buying the first pullback."],
  "Liquidity sweep": ["Sweep of equal lows followed by reclaim.", "Stop run above prior high, expecting rejection."],
  "Support/resistance": ["Well-defined support tested three times.", "Rejection from weekly resistance."],
};
const LESSONS_GOOD = ["Patience paid off — waited for confirmation.", "Sized correctly and let the trade work.", "Took the planned exit without hesitation."];
const LESSONS_BAD = ["Entered before confirmation.", "Should have stopped after the second loss.", "Moved the stop instead of accepting the loss.", "Chased the move after missing the entry.", "Size was too big for the setup quality."];

// ─── Scenario generator ─────────────────────────────────────────────────────
type Scenario = "pass" | "breach-trailing" | "progress" | "funded" | "fail-daily" | "breach-static";

interface GenTrade {
  symbol: string;
  direction: Direction;
  openedAt: Date;
  entryPrice: number;
  stopLoss: number;
  takeProfit: number;
  quantity: number;
  exits: { price: number; quantity: number; exitedAt: Date }[];
  commission: number;
  swap: number;
  mfePrice: number;
  maePrice: number;
  strategy: string;
  setup: string;
  timeframe: string;
  marketCondition: string;
  confluences: string[];
  grade: TradeGrade;
  tags: string[];
  revenge: boolean;
  approxNet: number;
  notes: string | null;
  journal: Record<string, unknown> | null;
}

function* weekdays(fromKey: string, toKey: string) {
  const d = new Date(`${fromKey}T00:00:00Z`);
  const end = new Date(`${toKey}T00:00:00Z`);
  while (d <= end) {
    const wd = d.getUTCDay();
    if (wd !== 0 && wd !== 6) yield d.toISOString().slice(0, 10);
    d.setUTCDate(d.getUTCDate() + 1);
  }
}

function makeTrade(opts: {
  day: string;
  minuteUtc: number;
  inst: Inst;
  riskAmount: number;
  pWin: number;
  revenge: boolean;
  oversize?: boolean;
  forceLoss?: boolean;
}): GenTrade {
  const { inst } = opts;
  const strategy = pick(STRATEGIES);
  let pWin = opts.pWin + STRATEGY_EDGE[strategy];
  const tags: string[] = [];
  if (opts.revenge) {
    tags.push("Revenge trade");
    pWin -= 0.2;
  } else if (chance(0.06)) {
    tags.push(pick(["FOMO", "Chased trade", "Entered late"]));
    pWin -= 0.12;
  }
  if (opts.oversize) tags.push("Oversized");
  const direction: Direction = chance(0.55) ? "LONG" : "SHORT";
  const sign = direction === "LONG" ? 1 : -1;
  const entry = fix(nextPrice(inst), inst.tick);
  const stopDist = fix(between(inst.stop[0], inst.stop[1]), inst.tick);
  const risk = opts.riskAmount * (opts.revenge ? 1.5 : 1) * (opts.oversize ? 2 : 1);
  const quantity = Math.max(inst.lotStep, fix(risk / (stopDist * inst.pointValue), inst.lotStep));
  const plannedRR = fix(between(1.5, 3), 0.1);
  const stopLoss = fix(entry - sign * stopDist, inst.tick);
  const takeProfit = fix(entry + sign * stopDist * plannedRR, inst.tick);

  const win = !opts.forceLoss && chance(Math.max(0.05, Math.min(0.9, pWin)));
  const be = !win && !opts.forceLoss && chance(0.08);
  let r: number;
  if (win) r = chance(0.45) ? plannedRR : between(0.6, plannedRR);
  else if (be) r = 0;
  else r = chance(0.8) ? -1 : between(-1.25, -0.5);
  if (tags.includes("Took profit early")) r = Math.min(r, 0.6);
  if (win && !opts.revenge && chance(0.12)) {
    tags.push("Took profit early");
    r = Math.min(r, between(0.4, 0.9));
  }
  if (!win && !be && chance(0.1)) {
    tags.push("Moved stop");
    r = between(-1.6, -1.2);
  }
  if (!tags.length && chance(0.5)) tags.push("Followed plan");

  const openedAt = new Date(`${opts.day}T00:00:00Z`);
  openedAt.setUTCMinutes(opts.minuteUtc);
  const duration = int(8, 170);
  const exitedAt = new Date(openedAt.getTime() + duration * 60_000);
  const finalExit = fix(entry + sign * stopDist * r, inst.tick);
  const exits: GenTrade["exits"] = [];
  if (win && r > 1.2 && chance(0.3) && quantity >= inst.lotStep * 2) {
    const part = fix(quantity / 2, inst.lotStep);
    exits.push({ price: fix(entry + sign * stopDist, inst.tick), quantity: part, exitedAt: new Date(openedAt.getTime() + Math.floor(duration / 2) * 60_000) });
    exits.push({ price: finalExit, quantity: Number((quantity - part).toFixed(6)), exitedAt });
  } else {
    exits.push({ price: finalExit, quantity, exitedAt });
  }
  const commission = Number((inst.commissionPerLot * quantity).toFixed(2));
  const overnight = chance(0.04);
  const swap = overnight ? -Number((1.8 * quantity).toFixed(2)) : 0;
  if (overnight) exits[exits.length - 1].exitedAt = new Date(exitedAt.getTime() + 18 * 3600_000);
  const mfe = fix(entry + sign * stopDist * Math.max(r, 0) + sign * stopDist * between(0, 0.8), inst.tick);
  const mae = r <= -1 ? stopLoss : fix(entry - sign * stopDist * between(0.1, 0.9), inst.tick);
  const approxNet = r * stopDist * quantity * inst.pointValue - commission + swap;
  const mistake = tags.some((t) => t !== "Followed plan");
  const grade: TradeGrade = mistake ? pick(["C", "D", "F"] as const) : win ? pick(["A_PLUS", "A", "B"] as const) : pick(["A", "B", "C"] as const);

  const journal = chance(0.68)
    ? {
        reason: pick(THESES[strategy]),
        thesis: pick(THESES[strategy]),
        setupExplanation: `${strategy} on ${inst.symbol} — ${pick(SETUPS).toLowerCase()}.`,
        expectedOutcome: `Target ${plannedRR}R at the next liquidity pool.`,
        riskJustification: opts.revenge ? "Wanted to make back the previous loss." : "Stop beyond structure; risk within plan.",
        whatHappened: win ? "Price moved in my direction after a brief retest." : be ? "Stalled at entry; scratched it." : "Setup failed; stop was hit.",
        followedPlan: !mistake,
        changes: tags.includes("Moved stop") ? "Moved stop further away mid-trade." : null,
        wentWell: win ? pick(LESSONS_GOOD) : null,
        wentWrong: mistake ? pick(LESSONS_BAD) : null,
        lesson: mistake ? pick(LESSONS_BAD) : pick(LESSONS_GOOD),
        emotionalState: opts.revenge ? "Frustrated" : pick(["Calm", "Focused", "Slightly anxious", "Confident"]),
        mistakes: mistake ? tags.filter((t) => t !== "Followed plan").join(", ") : null,
        confidence: int(mistake ? 2 : 3, 5),
        stress: int(opts.revenge ? 4 : 1, opts.revenge ? 5 : 3),
        fear: int(1, 3),
        greed: int(opts.revenge ? 3 : 1, opts.revenge ? 5 : 3),
        patience: int(mistake ? 1 : 3, mistake ? 3 : 5),
        fomo: int(tags.includes("FOMO") || tags.includes("Chased trade") ? 4 : 1, tags.includes("FOMO") ? 5 : 3),
        revenge: opts.revenge ? int(4, 5) : int(1, 2),
        boredom: int(1, 3),
        discipline: int(mistake ? 1 : 3, mistake ? 3 : 5),
      }
    : null;

  return {
    symbol: inst.symbol,
    direction,
    openedAt,
    entryPrice: entry,
    stopLoss,
    takeProfit,
    quantity,
    exits,
    commission,
    swap,
    mfePrice: mfe,
    maePrice: mae,
    strategy,
    setup: pick(SETUPS),
    timeframe: pick(TIMEFRAMES),
    marketCondition: pick(CONDITIONS),
    confluences: [pick(CONFLUENCES), ...(chance(0.5) ? [pick(CONFLUENCES)] : [])].filter((v, i, a) => a.indexOf(v) === i),
    grade,
    tags: [...new Set(tags)],
    revenge: opts.revenge,
    approxNet,
    notes: chance(0.2) ? `${strategy} ${direction.toLowerCase()} on ${inst.symbol}.` : null,
    journal,
  };
}

interface ScenarioCfg {
  scenario: Scenario;
  start: string;
  end?: string;
  startingBalance: number;
  symbols: string[];
  riskPct: [number, number];
  targetPct?: number;
  maxLossPct?: number;
  dailyLossPct?: number;
  minDays?: number;
  progressFraction?: number;
}

/** Generate trades day by day until the scenario's end condition. Returns trades + last day. */
function runScenario(cfg: ScenarioCfg): { trades: GenTrade[]; lastDay: string } {
  const trades: GenTrade[] = [];
  let balance = cfg.startingBalance;
  let hwm = balance;
  let tradingDays = 0;
  let lastDay = cfg.start;
  const pWinBase = { pass: 0.56, "breach-trailing": 0.34, progress: 0.52, funded: 0.5, "fail-daily": 0.48, "breach-static": 0.3 }[cfg.scenario];
  let dayIndex = 0;
  let boost = 0;
  for (const day of weekdays(cfg.start, cfg.end ?? LAST_DAY)) {
    dayIndex++;
    if (chance(cfg.scenario === "funded" ? 0.5 : 0.25)) continue; // not every weekday is traded
    const overtrade = chance(0.1);
    const bad = cfg.scenario === "fail-daily" && dayIndex > 6;
    let n = bad ? 6 : overtrade ? int(4, 6) : int(1, 3);
    let minute = pick([7 * 60 + int(0, 150), 13 * 60 + 30 + int(0, 120), 1 * 60 + int(0, 240)]);
    let prevLoss = false;
    let dayPnl = 0;
    const dayStart = balance;
    tradingDays++;
    lastDay = day;
    while (n-- > 0) {
      const revenge = prevLoss && chance(0.4);
      const riskAmt = balance * between(cfg.riskPct[0], cfg.riskPct[1]) / 100;
      const t = makeTrade({
        day,
        minuteUtc: minute,
        inst: INSTRUMENTS[pick(cfg.symbols)],
        riskAmount: riskAmt,
        pWin: pWinBase + boost,
        revenge,
        oversize: bad && n < 3,
        forceLoss: bad,
      });
      trades.push(t);
      balance += t.approxNet;
      dayPnl += t.approxNet;
      if (cfg.scenario === "funded" || cfg.scenario === "progress" || cfg.scenario === "pass") {
        // Stop for the day after a large loss — protects the scenario from accidental breaches.
        if (cfg.dailyLossPct && -dayPnl > (cfg.dailyLossPct / 100) * cfg.startingBalance * 0.6) break;
      }
      prevLoss = t.approxNet < 0;
      const last = t.exits[t.exits.length - 1].exitedAt;
      minute = Math.floor((last.getTime() - new Date(`${day}T00:00:00Z`).getTime()) / 60000) + (revenge ? int(2, 8) : int(15, 90));
      if (minute > 22 * 60) break;
    }
    if (cfg.scenario === "breach-trailing") hwm = Math.max(hwm, balance);
    const profit = balance - cfg.startingBalance;
    if (cfg.scenario === "pass" && cfg.targetPct && profit >= (cfg.targetPct / 100) * cfg.startingBalance * 1.02 && tradingDays >= (cfg.minDays ?? 0)) break;
    if (cfg.scenario === "progress" && cfg.targetPct && profit >= (cfg.targetPct / 100) * cfg.startingBalance * (cfg.progressFraction ?? 0.6)) break;
    if (cfg.scenario === "breach-trailing" && cfg.maxLossPct && balance < Math.min(hwm - (cfg.maxLossPct / 100) * cfg.startingBalance, cfg.startingBalance) ) break;
    if (cfg.scenario === "breach-static" && cfg.maxLossPct && balance < cfg.startingBalance * (1 - cfg.maxLossPct / 100)) break;
    if (cfg.scenario === "fail-daily" && cfg.dailyLossPct && dayStart - balance > (cfg.dailyLossPct / 100) * cfg.startingBalance) break;
    // Keep in-progress / passing scenarios from wandering into a breach.
    if ((cfg.scenario === "pass" || cfg.scenario === "progress") && cfg.maxLossPct && balance < cfg.startingBalance * (1 - (cfg.maxLossPct / 100) * 0.55)) {
      boost = 0.12;
    }
  }
  return { trades, lastDay };
}

// ─── Seeding ────────────────────────────────────────────────────────────────
async function main() {
  const existing = await prisma.user.findUnique({ where: { email: DEMO_EMAIL } });
  if (existing) await prisma.user.delete({ where: { id: existing.id } });

  const userId = `demo_${Date.now().toString(36)}`;
  await prisma.user.create({ data: { id: userId, name: "Demo Trader", email: DEMO_EMAIL, emailVerified: true } });
  await prisma.authAccount.create({
    data: { id: `cred_${userId}`, accountId: userId, providerId: "credential", userId, password: await hashPassword(DEMO_PASSWORD) },
  });
  await provisionNewUser(userId);
  await prisma.userSettings.update({
    where: { userId },
    data: { timezone: "Europe/London", defaultCurrency: "USD", riskPercent: 1, maxTradesPerDay: 4, maxDailyLossPct: 2, defaultRR: 2, insightMinTrades: 20 },
  });
  await prisma.exchangeRate.create({ data: { userId, base: "EUR", quote: "USD", rate: 1.08 } });
  await prisma.tradingRule.createMany({
    data: [
      { userId, type: "MAX_RISK_PER_TRADE_PCT", value: 1 },
      { userId, type: "MAX_LOSING_TRADES_PER_DAY", value: 2 },
      { userId, type: "MAX_DAILY_LOSS_PCT", value: 2 },
      { userId, type: "MAX_TRADES_PER_DAY", value: 4 },
      { userId, type: "TRADING_HOURS", startMinute: 7 * 60, endMinute: 20 * 60 },
    ],
  });

  const [strategies, tags, instruments] = await Promise.all([
    prisma.strategy.findMany({ where: { userId } }),
    prisma.tradeTag.findMany({ where: { userId } }),
    prisma.instrument.findMany({ where: { userId } }),
  ]);
  const strategyId = (name: string) => strategies.find((s) => s.name === name)!.id;
  const tagId = (name: string) => tags.find((t) => t.name === name)!.id;
  const instrumentId = (symbol: string) => instruments.find((i) => i.symbol === symbol)!.id;

  const firms = {
    northwind: await prisma.propFirm.create({ data: { userId, name: "Northwind Funding (Demo)", website: "https://example.com/northwind", notes: "Fictional firm for demo data." } }),
    summit: await prisma.propFirm.create({ data: { userId, name: "Summit Prop (Demo)", website: "https://example.com/summit", notes: "Fictional firm — trailing end-of-day drawdown." } }),
    atlas: await prisma.propFirm.create({ data: { userId, name: "Atlas Traders Fund (Demo)", website: "https://example.com/atlas", notes: "Fictional firm — EUR and USD accounts." } }),
  };

  const addDays = (key: string, n: number) => {
    const d = new Date(`${key}T00:00:00Z`);
    d.setUTCDate(d.getUTCDate() + n);
    return d.toISOString().slice(0, 10);
  };
  const at = (key: string, hh = 9) => new Date(`${key}T${String(hh).padStart(2, "0")}:00:00Z`);

  async function createAccount(a: {
    firmId: string;
    name: string;
    number: string;
    size: number;
    currency?: string;
    type: AccountType;
    phase?: number | null;
    status: AccountStatus;
    start: string;
    fee?: { amount: number; type?: "CHALLENGE" | "RESET" | "ACTIVATION"; currency?: string };
    parentId?: string;
    rule: {
      profitTargetPct?: number | null;
      maxDailyLossPct?: number;
      maxOverallLossPct?: number;
      drawdownType?: DrawdownType;
      trailingLocksAtStart?: boolean;
      minTradingDays?: number | null;
      consistencyPct?: number | null;
      payoutThresholdAmount?: number | null;
      payoutFrequencyDays?: number | null;
      profitSplitPct?: number | null;
      weekendHoldingAllowed?: boolean;
      maxPositionSize?: number | null;
      dayResetHour?: number;
      dayResetTimezone?: string | null;
    };
  }) {
    return prisma.tradingAccount.create({
      data: {
        userId,
        propFirmId: a.firmId,
        parentAccountId: a.parentId,
        name: a.name,
        accountNumber: a.number,
        accountSize: a.size,
        startingBalance: a.size,
        currency: a.currency ?? "USD",
        accountType: a.type,
        phase: a.phase ?? null,
        status: a.status,
        purchasedAt: a.fee ? at(addDays(a.start, -1), 18) : null,
        startedAt: at(a.start, 6),
        rule: { create: a.rule },
        fees: a.fee ? { create: { type: a.fee.type ?? "CHALLENGE", amount: a.fee.amount, currency: a.fee.currency ?? a.currency ?? "USD", paidAt: at(addDays(a.start, -1), 18) } } : undefined,
      },
    });
  }

  async function insertTrades(accountId: string, list: GenTrade[], opts: { groupWith?: Map<number, string> } = {}) {
    const ids: string[] = [];
    for (let i = 0; i < list.length; i++) {
      const t = list[i];
      const closedAt = t.exits[t.exits.length - 1].exitedAt;
      const trade = await prisma.trade.create({
        data: {
          userId,
          accountId,
          instrumentId: instrumentId(t.symbol),
          symbol: t.symbol,
          direction: t.direction,
          status: "CLOSED",
          openedAt: t.openedAt,
          closedAt,
          entryPrice: t.entryPrice,
          stopLoss: t.stopLoss,
          takeProfit: t.takeProfit,
          quantity: t.quantity,
          pointValue: INSTRUMENTS[t.symbol].pointValue,
          commission: t.commission,
          swap: t.swap,
          mfePrice: t.mfePrice,
          maePrice: t.maePrice,
          strategyId: strategyId(t.strategy),
          setup: t.setup,
          timeframe: t.timeframe,
          tradeType: "Intraday",
          entryModel: pick(["Market", "Limit", "Retest confirmation"]),
          confluences: t.confluences,
          marketCondition: t.marketCondition,
          grade: t.grade,
          notes: t.notes,
          groupId: opts.groupWith?.get(i) ?? null,
          source: "MANUAL",
          fingerprint: tradeFingerprint({ accountId, symbol: t.symbol, direction: t.direction, openedAt: t.openedAt, entryPrice: t.entryPrice, closedAt, exitPrice: t.exits[t.exits.length - 1].price, quantity: t.quantity }),
          exits: { create: t.exits },
          tags: { create: t.tags.map((name) => ({ tagId: tagId(name) })) },
          journal: t.journal ? { create: t.journal } : undefined,
        },
      });
      ids.push(trade.id);
    }
    return ids;
  }

  async function events(accountId: string, list: { type: AccountEventType; day: string; hour?: number; amount?: number; from?: AccountStatus; to?: AccountStatus; notes?: string }[]) {
    await prisma.accountEvent.createMany({
      data: list.map((e) => ({ accountId, type: e.type, occurredAt: at(e.day, e.hour ?? 12), amount: e.amount ?? null, fromStatus: e.from ?? null, toStatus: e.to ?? null, notes: e.notes ?? null })),
    });
  }

  const created: { id: string; name: string; expect: string }[] = [];

  // ── Northwind: 2-step → funded with payouts ──
  const nwRule = { maxDailyLossPct: 5, maxOverallLossPct: 10, drawdownType: "STATIC" as const, weekendHoldingAllowed: true };
  const p1Start = "2026-01-12";
  const p1Gen = runScenario({ scenario: "pass", start: p1Start, startingBalance: 10000, symbols: ["EURUSD", "GBPUSD", "XAUUSD"], riskPct: [0.6, 1], targetPct: 8, maxLossPct: 10, dailyLossPct: 5, minDays: 4 });
  const p1 = await createAccount({ firmId: firms.northwind.id, name: "NW 10K — Phase 1", number: "NW-10-48211", size: 10000, type: "TWO_STEP", phase: 1, status: "PASSED", start: p1Start, fee: { amount: 89 }, rule: { ...nwRule, profitTargetPct: 8, minTradingDays: 4 } });
  await insertTrades(p1.id, p1Gen.trades);
  await events(p1.id, [
    { type: "CHALLENGE_PURCHASED", day: addDays(p1Start, -1), hour: 18, amount: 89 },
    { type: "CHALLENGE_STARTED", day: p1Start, hour: 6 },
    { type: "PHASE_PASSED", day: addDays(p1Gen.lastDay, 1), from: "CHALLENGE", to: "PASSED" },
  ]);
  created.push({ id: p1.id, name: p1.name, expect: "target reached" });

  const p2Start = addDays(p1Gen.lastDay, 3);
  const p2Gen = runScenario({ scenario: "pass", start: p2Start, startingBalance: 10000, symbols: ["EURUSD", "GBPUSD", "XAUUSD"], riskPct: [0.5, 0.9], targetPct: 5, maxLossPct: 10, dailyLossPct: 5, minDays: 4 });
  const p2 = await createAccount({ firmId: firms.northwind.id, parentId: p1.id, name: "NW 10K — Phase 2", number: "NW-10-48944", size: 10000, type: "TWO_STEP", phase: 2, status: "PASSED", start: p2Start, rule: { ...nwRule, profitTargetPct: 5, minTradingDays: 4 } });
  await insertTrades(p2.id, p2Gen.trades);
  await events(p2.id, [
    { type: "CHALLENGE_STARTED", day: p2Start, hour: 6, notes: "Continued from NW 10K — Phase 1" },
    { type: "CHALLENGE_PASSED", day: addDays(p2Gen.lastDay, 1), from: "CHALLENGE", to: "PASSED" },
  ]);
  created.push({ id: p2.id, name: p2.name, expect: "target reached" });

  const fStart = addDays(p2Gen.lastDay, 6);
  const fGen = runScenario({ scenario: "funded", start: fStart, startingBalance: 10000, symbols: ["EURUSD", "GBPUSD", "XAUUSD"], riskPct: [0.5, 0.8], maxLossPct: 10, dailyLossPct: 5 });
  const funded = await createAccount({
    firmId: firms.northwind.id,
    parentId: p2.id,
    name: "NW 10K — Funded",
    number: "NW-F-10-50317",
    size: 10000,
    type: "FUNDED",
    status: "FUNDED",
    start: fStart,
    rule: { ...nwRule, payoutThresholdAmount: 100, payoutFrequencyDays: 14, profitSplitPct: 80 },
  });
  await events(funded.id, [{ type: "FUNDED_ACTIVATED", day: fStart, hour: 6, notes: "Continued from NW 10K — Phase 2" }]);

  // ── Atlas EUR instant funded, with copies of some Northwind funded trades ──
  const eurStart = "2026-05-04";
  const eurAccount = await createAccount({
    firmId: firms.atlas.id,
    name: "Atlas €20K Instant",
    number: "ATL-EUR-20-7781",
    size: 20000,
    currency: "EUR",
    type: "INSTANT_FUNDED",
    status: "PAYOUT_RECEIVED",
    start: eurStart,
    fee: { amount: 229, currency: "EUR" },
    rule: { maxDailyLossPct: 5, maxOverallLossPct: 8, drawdownType: "STATIC", payoutThresholdAmount: 200, payoutFrequencyDays: 30, profitSplitPct: 75, weekendHoldingAllowed: false },
  });
  await events(eurAccount.id, [
    { type: "CHALLENGE_PURCHASED", day: addDays(eurStart, -1), hour: 18, amount: 229, notes: "Instant funding — no evaluation" },
    { type: "FUNDED_ACTIVATED", day: eurStart, hour: 6 },
  ]);

  // Copy ~40% of the funded trades after eurStart onto the EUR account (same idea, 1.5× size).
  const groupFor = new Map<number, string>();
  const eurCopies: GenTrade[] = [];
  const copyGroups: string[] = [];
  for (let i = 0; i < fGen.trades.length; i++) {
    const t = fGen.trades[i];
    if (t.openedAt.toISOString().slice(0, 10) < eurStart || !chance(0.4)) continue;
    const g = await prisma.tradeGroup.create({ data: { userId, label: `${t.symbol} ${t.direction.toLowerCase()}` } });
    groupFor.set(i, g.id);
    copyGroups.push(g.id);
    const step = INSTRUMENTS[t.symbol].lotStep;
    eurCopies.push({
      ...t,
      quantity: fix(t.quantity * 1.5, step),
      exits: t.exits.map((e) => ({ ...e, quantity: fix(e.quantity * 1.5, step) })),
      commission: Number((t.commission * 1.5).toFixed(2)),
      swap: Number((t.swap * 1.5).toFixed(2)),
      journal: null,
    });
  }
  await insertTrades(funded.id, fGen.trades, { groupWith: groupFor });
  const eurOwn = runScenario({ scenario: "funded", start: eurStart, startingBalance: 20000, symbols: ["NAS100", "US30"], riskPct: [0.2, 0.35], maxLossPct: 8, dailyLossPct: 4 });
  await insertTrades(eurAccount.id, eurCopies, { groupWith: new Map(copyGroups.map((g, i) => [i, g])) });
  // Keep the account's own trades off days that already carry copied trades (avoids stacking daily risk).
  const copyDays = new Set(eurCopies.map((t) => t.openedAt.toISOString().slice(0, 10)));
  await insertTrades(eurAccount.id, eurOwn.trades.filter((t) => !copyDays.has(t.openedAt.toISOString().slice(0, 10))));

  // ── Summit: 1-step breached (trailing EOD) → reset in progress ──
  const s1Start = "2026-02-02";
  const summitRule = { profitTargetPct: 10, maxDailyLossPct: 4, maxOverallLossPct: 6, drawdownType: "TRAILING_EOD" as const, trailingLocksAtStart: true, minTradingDays: 3, consistencyPct: 40, dayResetHour: 17, dayResetTimezone: "America/New_York" };
  const s1Gen = runScenario({ scenario: "breach-trailing", start: s1Start, startingBalance: 50000, symbols: ["NAS100", "US30", "XAUUSD"], riskPct: [0.7, 1.1], maxLossPct: 6 });
  const s1 = await createAccount({ firmId: firms.summit.id, name: "Summit 50K Challenge", number: "SUM-50-11902", size: 50000, type: "ONE_STEP", status: "BREACHED", start: s1Start, fee: { amount: 165 }, rule: summitRule });
  await insertTrades(s1.id, s1Gen.trades);
  await events(s1.id, [
    { type: "CHALLENGE_PURCHASED", day: addDays(s1Start, -1), hour: 18, amount: 165 },
    { type: "CHALLENGE_STARTED", day: s1Start, hour: 6 },
    { type: "ACCOUNT_BREACHED", day: s1Gen.lastDay, hour: 20, from: "CHALLENGE", to: "BREACHED", notes: "Trailing drawdown hit." },
  ]);
  await prisma.tradingAccount.update({ where: { id: s1.id }, data: { endedAt: at(s1Gen.lastDay, 20) } });
  created.push({ id: s1.id, name: s1.name, expect: "breached" });

  const s2Start = "2026-08-17";
  const s2Gen = runScenario({ scenario: "progress", start: s2Start, startingBalance: 50000, symbols: ["NAS100", "US30"], riskPct: [0.4, 0.7], targetPct: 10, maxLossPct: 6, dailyLossPct: 4, progressFraction: 0.62 });
  const s2 = await createAccount({ firmId: firms.summit.id, parentId: s1.id, name: "Summit 50K Challenge — Reset", number: "SUM-50-13377", size: 50000, type: "ONE_STEP", status: "CHALLENGE", start: s2Start, fee: { amount: 99, type: "RESET" }, rule: summitRule });
  await insertTrades(s2.id, s2Gen.trades);
  await events(s2.id, [
    { type: "ACCOUNT_RESET", day: addDays(s2Start, -1), hour: 18, amount: 99, notes: "Reset after breach of Summit 50K Challenge" },
    { type: "CHALLENGE_STARTED", day: s2Start, hour: 6 },
  ]);
  created.push({ id: s2.id, name: s2.name, expect: "in progress" });

  // ── Atlas USD 2-step: breached on daily loss, then failed retry ──
  const a1Start = "2026-04-06";
  const atlasRule = { profitTargetPct: 8, maxDailyLossPct: 5, maxOverallLossPct: 10, drawdownType: "STATIC" as const, minTradingDays: 4 };
  const a1Gen = runScenario({ scenario: "fail-daily", start: a1Start, startingBalance: 25000, symbols: ["EURUSD", "BTCUSD", "GBPUSD"], riskPct: [0.8, 1.2], dailyLossPct: 5 });
  const a1 = await createAccount({ firmId: firms.atlas.id, name: "Atlas 25K — Phase 1", number: "ATL-25-30871", size: 25000, type: "TWO_STEP", phase: 1, status: "BREACHED", start: a1Start, fee: { amount: 145 }, rule: atlasRule });
  await insertTrades(a1.id, a1Gen.trades);
  await events(a1.id, [
    { type: "CHALLENGE_PURCHASED", day: addDays(a1Start, -1), hour: 18, amount: 145 },
    { type: "CHALLENGE_STARTED", day: a1Start, hour: 6 },
    { type: "ACCOUNT_BREACHED", day: a1Gen.lastDay, hour: 20, from: "CHALLENGE", to: "BREACHED", notes: "Daily loss limit exceeded after revenge trading." },
  ]);
  await prisma.tradingAccount.update({ where: { id: a1.id }, data: { endedAt: at(a1Gen.lastDay, 20) } });
  created.push({ id: a1.id, name: a1.name, expect: "breached" });

  const a2Start = addDays(a1Gen.lastDay, 7);
  const a2Gen = runScenario({ scenario: "breach-static", start: a2Start, startingBalance: 25000, symbols: ["EURUSD", "BTCUSD"], riskPct: [0.9, 1.3], maxLossPct: 10 });
  const a2 = await createAccount({ firmId: firms.atlas.id, parentId: a1.id, name: "Atlas 25K — Phase 1 (retry)", number: "ATL-25-31555", size: 25000, type: "TWO_STEP", phase: 1, status: "FAILED", start: a2Start, fee: { amount: 145 }, rule: atlasRule });
  await insertTrades(a2.id, a2Gen.trades);
  await events(a2.id, [
    { type: "CHALLENGE_PURCHASED", day: addDays(a2Start, -1), hour: 18, amount: 145 },
    { type: "CHALLENGE_STARTED", day: a2Start, hour: 6 },
    { type: "ACCOUNT_FAILED", day: a2Gen.lastDay, hour: 20, from: "CHALLENGE", to: "FAILED", notes: "Max loss reached." },
  ]);
  await prisma.tradingAccount.update({ where: { id: a2.id }, data: { endedAt: at(a2Gen.lastDay, 20) } });
  created.push({ id: a2.id, name: a2.name, expect: "breached" });

  // ── Build derived data, then add payouts based on the actual computed balances ──
  for (const a of [p1, p2, funded, eurAccount, s1, s2, a1, a2]) await rebuildAccount(userId, a.id);

  async function addPayouts(accountId: string, currency: string, split: number, every: number, finalRequested: boolean) {
    const trades = await prisma.trade.findMany({ where: { accountId }, orderBy: { closedAt: "asc" }, select: { closedAt: true, netPnl: true } });
    const account = await prisma.tradingAccount.findUniqueOrThrow({ where: { id: accountId } });
    const start = Number(account.startingBalance);
    let balance = start;
    let lastPayoutDay = account.startedAt!.toISOString().slice(0, 10);
    const payouts: { requested: string; amount: number }[] = [];
    for (const t of trades) {
      balance += Number(t.netPnl);
      const day = t.closedAt!.toISOString().slice(0, 10);
      const daysSince = (Date.parse(day) - Date.parse(lastPayoutDay)) / 86_400_000;
      if (daysSince >= every && balance - start >= 300) {
        const amount = Math.floor((balance - start) * 0.9);
        payouts.push({ requested: addDays(day, 1), amount });
        balance -= amount;
        lastPayoutDay = addDays(day, 1);
      }
    }
    for (let i = 0; i < payouts.length; i++) {
      const p = payouts[i];
      const isLast = i === payouts.length - 1;
      const pending = isLast && finalRequested && addDays(p.requested, 6) > LAST_DAY;
      const received = Number((p.amount * split / 100).toFixed(2));
      await prisma.payout.create({
        data: {
          userId,
          accountId,
          status: pending ? "REQUESTED" : "PAID",
          requestedAt: at(p.requested, 10),
          approvedAt: pending ? null : at(addDays(p.requested, 2), 10),
          paidAt: pending ? null : at(addDays(p.requested, 5), 10),
          amountRequested: p.amount,
          amountReceived: pending ? null : received,
          profitSplitPct: split,
          fees: 0,
          paymentMethod: pick(["Bank transfer", "Rise", "Crypto (USDT)"]),
          currency,
          notes: i === 0 ? "First payout" : null,
        },
      });
      await events(accountId, [
        { type: "PAYOUT_REQUESTED", day: p.requested, hour: 10, amount: p.amount },
        ...(pending ? [] : [
          { type: "PAYOUT_APPROVED" as const, day: addDays(p.requested, 2), hour: 10, amount: p.amount },
          { type: "PAYOUT_RECEIVED" as const, day: addDays(p.requested, 5), hour: 10, amount: received },
        ]),
      ]);
    }
    return payouts.length;
  }
  const nwPayouts = await addPayouts(funded.id, "USD", 80, 21, true);
  const eurPayouts = await addPayouts(eurAccount.id, "EUR", 75, 30, false);
  // A rejected request for completeness of payout states.
  await prisma.payout.create({
    data: { userId, accountId: eurAccount.id, status: "REJECTED", requestedAt: at("2026-06-01", 10), amountRequested: 150, currency: "EUR", deductFromBalance: false, notes: "Below minimum payout threshold." },
  });
  await events(eurAccount.id, [{ type: "PAYOUT_REJECTED", day: "2026-06-02", hour: 10, amount: 150, notes: "Below minimum threshold" }]);
  await rebuildAccount(userId, funded.id);
  await rebuildAccount(userId, eurAccount.id);
  created.push({ id: funded.id, name: funded.name, expect: "funded" }, { id: eurAccount.id, name: eurAccount.name, expect: "funded" });

  // ── Verify statuses against the rule engine ──
  const total = await prisma.trade.count({ where: { userId } });
  console.log(`Seeded ${total} trades across ${created.length} accounts (payouts: NW ${nwPayouts}, EUR ${eurPayouts}).`);
  for (const c of created) {
    const s = await getAccountState(userId, c.id);
    if (!s) continue;
    const summary = [
      `balance ${s.balance.toFixed(2)}`,
      s.profitTarget ? `target ${s.profitTarget.progressPct.toFixed(1)}%` : null,
      s.overallLoss ? `DD left ${s.overallLoss.remaining.toFixed(2)}` : null,
      `breached=${s.breached}`,
      `passEligible=${s.passEligible}`,
    ].filter(Boolean).join(", ");
    const ok =
      c.expect === "breached" ? s.breached : c.expect === "target reached" ? s.passEligible : c.expect === "in progress" ? !s.breached && !s.passEligible : !s.breached;
    console.log(`${ok ? "✓" : "✗"} ${c.name} (${c.expect}): ${summary}`);
  }
  console.log(`\nDemo login: ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
